@baseUrl = http://Url:Port
@authToken = token

### 1️⃣ User Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "emma@example.com",
  "password": "password123"
}

### 2️⃣ Patient Signup
POST {{baseUrl}}/signUp
Content-Type: application/json

{
  "name": "Emmanuel",
  "email": "emma@example.com",
  "password": "password123"
}

### 3️⃣ Doctor Signup
POST {{baseUrl}}/doc-signUp
Content-Type: application/json

{
  "name": "Doctor",
  "email": "doctor@example.com",
  "password": "password123"
}

### 4️⃣ Admin Signup
POST {{baseUrl}}/admin/signUp
Content-Type: application/json

{
  "name": "Admin User",
  "email": "adminuser01@example.com",
  "password": "admin123",
  "role": "PATIENT"
}

### 5️⃣ Get Profile
GET {{baseUrl}}/profile
Authorization: Bearer {{authToken}}

### 6️⃣ Get All Users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### 7️⃣ Create Note
POST {{baseUrl}}/note
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Patient reports dizziness and shortness of breath. Ordered CBC immediately. Schedule cardiology consultation within 48 hours. Advise low-sodium diet. Monitor BP daily for 7 days. Follow up every 3 days for 2 weeks.",
  "patientId": "f298c252-3b5c-4c03-8f31-278d19e0ff6c"
}

### 8️⃣ Patient Selects Doctor  
POST {{baseUrl}}/patient/assign-doctor
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "doctorId": "f298c252-3b5c-4c03-8f31-278d19e0ff6c"
}
