@baseUrl = http://localhost:3000 
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjYTIwZmJmLTcwYmUtNDE2Ni1iZTMwLWZmY2NhOWFiYjYxOSIsImlhdCI6MTczOTQ4OTk3OCwiZXhwIjoxNzM5NTMzMTc4fQ.FsJnq9VcqkpSb6rIYA9ODc17MeHQtbGIF0Gv1Bov8sM
### 1️⃣ User Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "doctor@example.com",
  "password": "password123"
}

### 2️⃣ Patient Signup Request
POST {{baseUrl}}/signUp
Content-Type: application/json

{
  "name": "Emmanuel",
  "email": "emma@example.com",
  "password": "password123"
}

### 3️⃣ Doctor Signup Request
POST {{baseUrl}}/doc-signUp
Content-Type: application/json

{
  "name": "Doctor",
  "email": "doctor@example.com",
  "password": "password123"
}

### 4️⃣ Admin Signup Request (for Patient, Doctor, or Admin)
POST {{baseUrl}}/admin/signUp
Content-Type: application/json

{
  "name": "Admin User",
  "email": "adminuser01@example.com",
  "password": "admin123",
  "role": "PATIENT"
}

### 5️⃣ Get Profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 5️⃣ Get All Users
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 6️⃣ Create Note
POST {{baseUrl}}/note
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Patient reports dizziness and shortness of breath. Ordered complete blood count (CBC) immediately. Schedule a cardiology consultation within 48 hours. Advise the patient to avoid strenuous activity and maintain a low-sodium diet. Monitor blood pressure daily for 7 days. Follow up with the patient every 3 days for 2 weeks.",
  "patientId" : "7be9e1e7-5ee3-4645-aac9-8172ca163475"
}
